// sampleData.js - Sabaragamuwa University of Sri Lanka (SUSL) - DIGITAL ECO MANAYA Dataset
const INITIAL_CAMPUS_TREES = [
  {
    id: "tree-001",
    tagId: "SUSL-ECO-001",
    commonName: "Na Tree (නා ගස)",
    scientificName: "Mesua ferrea",
    family: "Calophyllaceae",
    category: "Endemic / National Heritage",
    zone: "Main Administration & Heritage Lawn",
    lat: 6.7148,
    lng: 80.7872,
    healthStatus: "Thriving",
    height: 14.5,
    dbh: 52,
    plantedDate: "2016-06-05",
    caretaker: "SUSL Nature & Adventure Society",
    wateringSchedule: "Natural mist & rainfall / Bi-weekly inspection",
    carbonOffsetKg: 215.4,
    notes: "Planted during the university founding anniversary celebration. Majestic canopy thriving in the scenic campus climate.",
    imageUrl: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-08-25"
  },
  {
    id: "tree-002",
    tagId: "SUSL-AGR-014",
    commonName: "Kumbuk Tree (කුඹුක් ගස)",
    scientificName: "Terminalia arjuna",
    family: "Combretaceae",
    category: "Medicinal / Riparian",
    zone: "Faculty of Agricultural Sciences",
    lat: 6.7162,
    lng: 80.7885,
    healthStatus: "Healthy",
    height: 18.0,
    dbh: 72,
    plantedDate: "2014-03-22",
    caretaker: "Dept. of Export Agriculture (Green Circle)",
    wateringSchedule: "Riverbed natural hydration",
    carbonOffsetKg: 345.8,
    notes: "Grows adjacent to the campus tributary stream. Deep root system acts as an embankment stabilizer preventing soil erosion.",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-08-30"
  },
  {
    id: "tree-003",
    tagId: "SUSL-GEO-007",
    commonName: "Mee Tree (මී ගස)",
    scientificName: "Madhuca longifolia",
    family: "Sapotaceae",
    category: "Medicinal / Indigenous",
    zone: "Faculty of Geomatics",
    lat: 6.7135,
    lng: 80.7860,
    healthStatus: "Thriving",
    height: 10.2,
    dbh: 42,
    plantedDate: "2019-11-15",
    caretaker: "Surveying & Geodesy Student Union",
    wateringSchedule: "Weekly",
    carbonOffsetKg: 135.0,
    notes: "Located near the Geomatics surveying observation benchmark. Dense canopy providing natural bird roosting and honey bee habitats.",
    imageUrl: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-09-02"
  },
  {
    id: "tree-004",
    tagId: "SUSL-APP-009",
    commonName: "Jak Tree / Kos (කොස් ගස)",
    scientificName: "Artocarpus heterophyllus",
    family: "Moraceae",
    category: "Food Security / Agroforestry",
    zone: "Faculty of Applied Sciences",
    lat: 6.7155,
    lng: 80.7892,
    healthStatus: "Healthy",
    height: 15.4,
    dbh: 58,
    plantedDate: "2015-08-10",
    caretaker: "Dept. of Food Science & Technology",
    wateringSchedule: "Weekly",
    carbonOffsetKg: 280.0,
    notes: "Provides organic fruits for practical food processing experiments. Healthy canopy and excellent yield.",
    imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-09-04"
  },
  {
    id: "tree-005",
    tagId: "SUSL-TEC-003",
    commonName: "Flamboyant / Mal Mara (මල් මාර)",
    scientificName: "Delonix regia",
    family: "Fabaceae",
    category: "Ornamental / Shade",
    zone: "Faculty of Technology",
    lat: 6.7128,
    lng: 80.7878,
    healthStatus: "Needs Care",
    height: 8.5,
    dbh: 34,
    plantedDate: "2021-04-12",
    caretaker: "Engineering Technology Club",
    wateringSchedule: "Daily during dry weather",
    carbonOffsetKg: 72.0,
    notes: "Mild stem borer attack detected on southern branch fork. Recommended organic neem oil treatment and mulch around trunk.",
    imageUrl: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-09-06"
  },
  {
    id: "tree-006",
    tagId: "SUSL-MAN-012",
    commonName: "Ceylon Ebony / Kaluwara (කළුවර)",
    scientificName: "Diospyros ebenum",
    family: "Ebenaceae",
    category: "Endemic / Conservation",
    zone: "Faculty of Management Studies",
    lat: 6.7142,
    lng: 80.7852,
    healthStatus: "Thriving",
    height: 7.2,
    dbh: 26,
    plantedDate: "2020-01-20",
    caretaker: "Management Eco Circle",
    wateringSchedule: "Twice a week",
    carbonOffsetKg: 58.5,
    notes: "Extremely precious conservation specimen. Monitored under Digital Eco Manaya biodiversity tracking protocol.",
    imageUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-09-01"
  },
  {
    id: "tree-007",
    tagId: "SUSL-ECO-025",
    commonName: "Mahogany (මහෝගනී)",
    scientificName: "Swietenia macrophylla",
    family: "Meliaceae",
    category: "Timber / Canopy",
    zone: "Riverine & Eco Trail",
    lat: 6.7168,
    lng: 80.7865,
    healthStatus: "Critical",
    height: 12.0,
    dbh: 46,
    plantedDate: "2017-09-18",
    caretaker: "SUSL Environmental Task Force",
    wateringSchedule: "Monthly inspection",
    carbonOffsetKg: 198.0,
    notes: "Suffered wind fracture during recent monsoon gusts. Bark fissure needs healing sealant and stabilization support.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    lastInspected: "2026-09-07"
  }
];
